# Form implementation generated from reading ui file 'windows_stacked_01.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1015, 718)
        
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 20, 1001, 671))
        self.stackedWidget.setObjectName("stackedWidget")
        
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        
        self.painting_image_random = QtWidgets.QLabel(parent=self.page_2)
        self.painting_image_random.setGeometry(QtCore.QRect(450, 130, 471, 491))
        self.painting_image_random.setText("")
        self.painting_image_random.setPixmap(QtGui.QPixmap("../example_paintings/Pablo_Picasso_412.jpg"))
        self.painting_image_random.setScaledContents(True)
        self.painting_image_random.setObjectName("painting_image_random")
        
        self.stackedWidget_2 = QtWidgets.QStackedWidget(parent=self.page_2)
        self.stackedWidget_2.setGeometry(QtCore.QRect(90, 310, 321, 301))
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        
        self.stack_01 = QtWidgets.QWidget()
        self.stack_01.setObjectName("stack_01")
        
        self.text_choose = QtWidgets.QLabel(parent=self.stack_01)
        self.text_choose.setGeometry(QtCore.QRect(30, 60, 241, 51))
        self.text_choose.setWordWrap(True)
        self.text_choose.setObjectName("text_choose")
        
        self.dop_down_artist = QtWidgets.QComboBox(parent=self.stack_01)
        self.dop_down_artist.setGeometry(QtCore.QRect(30, 120, 231, 71))
        self.dop_down_artist.setObjectName("dop_down_artist")
        self.dop_down_artist.addItem("")
        self.dop_down_artist.addItem("")
        
        self.stackedWidget_2.addWidget(self.stack_01)
        self.stack_02 = QtWidgets.QWidget()
        self.stack_02.setObjectName("stack_02")
        
        self.machine_answer = QtWidgets.QLabel(parent=self.stack_02)
        self.machine_answer.setGeometry(QtCore.QRect(10, 80, 281, 121))
        self.machine_answer.setObjectName("machine_answer")
        
        self.label = QtWidgets.QLabel(parent=self.stack_02)
        self.label.setGeometry(QtCore.QRect(90, 40, 141, 21))
        self.label.setObjectName("label")
        
        self.stackedWidget_2.addWidget(self.stack_02)
        
        self.pushButton_start2 = QtWidgets.QPushButton(parent=self.page_2)
        self.pushButton_start2.setGeometry(QtCore.QRect(100, 250, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_start2.setFont(font)
        self.pushButton_start2.setObjectName("pushButton_start2")
        self.text_start_request_2 = QtWidgets.QLabel(parent=self.page_2)
        self.text_start_request_2.setGeometry(QtCore.QRect(110, 140, 291, 81))
        self.text_start_request_2.setObjectName("text_start_request_2")
        self.title2 = QtWidgets.QLabel(parent=self.page_2)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.title2.setFont(font)
        self.title2.setObjectName("title2")
        self.stackedWidget.addWidget(self.page_2)
        
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.painting_image1 = QtWidgets.QLabel(parent=self.page_1)
        self.painting_image1.setGeometry(QtCore.QRect(110, 160, 181, 221))
        self.painting_image1.setText("")
        self.painting_image1.setPixmap(QtGui.QPixmap("../example_paintings/Vincent_van_Gogh_210.jpg"))
        self.painting_image1.setScaledContents(True)
        self.painting_image1.setObjectName("painting_image1")
        self.text_start_request = QtWidgets.QLabel(parent=self.page_1)
        self.text_start_request.setGeometry(QtCore.QRect(260, 460, 201, 31))
        self.text_start_request.setObjectName("text_start_request")
        self.pushButton_start_1 = QtWidgets.QPushButton(parent=self.page_1)
        self.pushButton_start_1.setGeometry(QtCore.QRect(490, 440, 401, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.pushButton_start_1.setFont(font)
        self.pushButton_start_1.setObjectName("pushButton_start_1")
        self.painting_image1_text = QtWidgets.QLabel(parent=self.page_1)
        self.painting_image1_text.setGeometry(QtCore.QRect(110, 390, 181, 21))
        self.painting_image1_text.setObjectName("painting_image1_text")
        self.painting_image2_text = QtWidgets.QLabel(parent=self.page_1)
        self.painting_image2_text.setGeometry(QtCore.QRect(310, 390, 181, 21))
        self.painting_image2_text.setObjectName("painting_image2_text")
        self.painting_image2 = QtWidgets.QLabel(parent=self.page_1)
        self.painting_image2.setGeometry(QtCore.QRect(310, 160, 181, 221))
        self.painting_image2.setText("")
        self.painting_image2.setPixmap(QtGui.QPixmap("../example_paintings/Vincent_van_Gogh_210.jpg"))
        self.painting_image2.setScaledContents(True)
        self.painting_image2.setObjectName("painting_image2")
        self.painting_image3_text = QtWidgets.QLabel(parent=self.page_1)
        self.painting_image3_text.setGeometry(QtCore.QRect(510, 390, 181, 21))
        self.painting_image3_text.setObjectName("painting_image3_text")
        self.painting_image3 = QtWidgets.QLabel(parent=self.page_1)
        self.painting_image3.setGeometry(QtCore.QRect(510, 160, 181, 221))
        self.painting_image3.setText("")
        self.painting_image3.setPixmap(QtGui.QPixmap("../example_paintings/Vincent_van_Gogh_210.jpg"))
        self.painting_image3.setScaledContents(True)
        self.painting_image3.setObjectName("painting_image3")
        self.painting_image4_text = QtWidgets.QLabel(parent=self.page_1)
        self.painting_image4_text.setGeometry(QtCore.QRect(710, 390, 181, 21))
        self.painting_image4_text.setObjectName("painting_image4_text")
        self.painting_image4 = QtWidgets.QLabel(parent=self.page_1)
        self.painting_image4.setGeometry(QtCore.QRect(710, 160, 181, 221))
        self.painting_image4.setText("")
        self.painting_image4.setPixmap(QtGui.QPixmap("../example_paintings/Vincent_van_Gogh_210.jpg"))
        self.painting_image4.setScaledContents(True)
        self.painting_image4.setObjectName("painting_image4")
        self.text_project = QtWidgets.QLabel(parent=self.page_1)
        self.text_project.setGeometry(QtCore.QRect(500, 530, 391, 51))
        self.text_project.setObjectName("text_project")
        self.title = QtWidgets.QLabel(parent=self.page_1)
        self.title.setGeometry(QtCore.QRect(350, 40, 318, 53))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.stackedWidget.addWidget(self.page_1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1015, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.stackedWidget_2.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.text_choose.setText(_translate("MainWindow", "Please choose your answer from the drop down menu below"))
        self.dop_down_artist.setItemText(0, _translate("MainWindow", "Picasso"))
        self.dop_down_artist.setItemText(1, _translate("MainWindow", "Gaugain"))
        self.machine_answer.setText(_translate("MainWindow", "example: Pablo Picasso \n"
"machine Answer \n"
"and all information gathered \n"
"by machine etc. \n"
"including correct answer"))
        self.label.setText(_translate("MainWindow", "Machine Answer"))
        self.pushButton_start2.setText(_translate("MainWindow", "Start"))
        self.text_start_request_2.setText(_translate("MainWindow", "push the start button to begin guessing \n"
"the artist who created the painting"))
        self.title2.setText(_translate("MainWindow", "Artist Recognition"))
        self.text_start_request.setText(_translate("MainWindow", "Click the start botton to begin"))
        self.pushButton_start_1.setText(_translate("MainWindow", "Start"))
        self.painting_image1_text.setText(_translate("MainWindow", "Artist name"))
        self.painting_image2_text.setText(_translate("MainWindow", "Artist name"))
        self.painting_image3_text.setText(_translate("MainWindow", "Artist name"))
        self.painting_image4_text.setText(_translate("MainWindow", "Artist name"))
        self.text_project.setText(_translate("MainWindow", "Description: Machine learns to recognize artist based \n"
"on a training set of 6000 paintings."))
        self.title.setText(_translate("MainWindow", "Artist Recognition"))
